# Generated by Django 5.2.5 on 2025-08-29 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TabelaPreco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome da tabela de preços', max_length=100)),
                ('tipo_veiculo', models.CharField(choices=[('carro', 'Carro'), ('moto', 'Moto'), ('van', 'Van'), ('caminhonete', 'Caminhonete')], max_length=15)),
                ('tipo_preco', models.CharField(choices=[('hora', 'Por Hora'), ('dia', 'Diária'), ('mensal', 'Mensal'), ('avulso', 'Avulso')], max_length=10)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tolerancia', models.PositiveIntegerField(default=15, help_text='Tolerância em minutos')),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tabelas_preco', to='core.unidade')),
            ],
            options={
                'verbose_name': 'Tabela de Preço',
                'verbose_name_plural': 'Tabelas de Preço',
                'unique_together': {('unidade', 'nome', 'tipo_veiculo', 'tipo_preco')},
            },
        ),
    ]
