# Generated by Django 5.2.5 on 2025-11-02 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoCobranca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoVeiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='tabelapreco',
            options={},
        ),
        migrations.RenameField(
            model_name='tabelapreco',
            old_name='ativo',
            new_name='ativa',
        ),
        migrations.AlterUniqueTogether(
            name='tabelapreco',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='tabelapreco',
            name='data_fim',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tabelapreco',
            name='data_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tabelapreco',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.RemoveField(
            model_name='tabelapreco',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='tabelapreco',
            name='tipo_preco',
        ),
        migrations.RemoveField(
            model_name='tabelapreco',
            name='tipo_veiculo',
        ),
        migrations.RemoveField(
            model_name='tabelapreco',
            name='tolerancia',
        ),
        migrations.RemoveField(
            model_name='tabelapreco',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='tabelapreco',
            name='valor',
        ),
        migrations.CreateModel(
            name='Preco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tabela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precos', to='parking.tabelapreco')),
                ('tipo_cobranca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking.tipocobranca')),
                ('tipo_veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking.tipoveiculo')),
            ],
            options={
                'unique_together': {('tabela', 'tipo_veiculo', 'tipo_cobranca')},
            },
        ),
    ]
