# Generated by Django 5.2.5 on 2025-09-04 00:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('core', '0002_remove_unidade_bairro_remove_unidade_cidade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='unidade',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='core.unidade'),
        ),
    ]
