# Generated by Django 5.2.5 on 2025-09-06 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_unidade'),
        ('core', '0002_remove_unidade_bairro_remove_unidade_cidade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='unidade',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='core.unidade'),
        ),
    ]
