# Generated by Django 5.2.5 on 2025-08-29 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Unidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('endereco', models.CharField(max_length=300)),
                ('rua', models.CharField(max_length=200)),
                ('numero', models.CharField(max_length=20)),
                ('bairro', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('vagasLivres', models.IntegerField(default=0)),
                ('vagasPresas', models.IntegerField(default=0)),
                ('horarioFuncionamento', models.TimeField()),
                ('codPessEmpresa', models.CharField(help_text='Sistema externo', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
