# Generated by Django 5.2.5 on 2025-09-06 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_unidade_bairro_remove_unidade_cidade_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unidade',
            name='horarioFuncionamento',
        ),
        migrations.AddField(
            model_name='unidade',
            name='horarioAbertura',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='unidade',
            name='horarioFechamento',
            field=models.TimeField(null=True),
        ),
    ]
