# Generated by Django 5.2.5 on 2025-10-25 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_unidade_horariofuncionamento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unidade',
            name='horarioAbertura',
        ),
        migrations.RemoveField(
            model_name='unidade',
            name='horarioFechamento',
        ),
        migrations.AddField(
            model_name='unidade',
            name='cnpj',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
        migrations.AddField(
            model_name='unidade',
            name='funciona_domingo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='unidade',
            name='funciona_feriados',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='unidade',
            name='funciona_quarta',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='unidade',
            name='funciona_quinta',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='unidade',
            name='funciona_sabado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='unidade',
            name='funciona_segunda',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='unidade',
            name='funciona_sexta',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='unidade',
            name='funciona_terca',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='unidade',
            name='horario_domingo_fim',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='unidade',
            name='horario_domingo_inicio',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='unidade',
            name='horario_quarta_fim',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='unidade',
            name='horario_quarta_inicio',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='unidade',
            name='horario_quinta_fim',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='unidade',
            name='horario_quinta_inicio',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='unidade',
            name='horario_sabado_fim',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='unidade',
            name='horario_sabado_inicio',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='unidade',
            name='horario_segunda_fim',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='unidade',
            name='horario_segunda_inicio',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='unidade',
            name='horario_sexta_fim',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='unidade',
            name='horario_sexta_inicio',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='unidade',
            name='horario_terca_fim',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='unidade',
            name='horario_terca_inicio',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='unidade',
            name='vagasManobráveis',
            field=models.IntegerField(default=0),
        ),
    ]
