# Generated by Django 5.2.5 on 2025-10-31 00:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_unidade_horarioabertura_and_more'),
        ('vehicles', '0002_tipoveiculo_veiculo_tipo_veiculo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unidade',
            options={'verbose_name': 'Unidade', 'verbose_name_plural': 'Unidades'},
        ),
        migrations.RemoveField(
            model_name='unidade',
            name='created_at',
        ),
        migrations.AddField(
            model_name='unidade',
            name='horarioAbertura',
            field=models.TimeField(null=True, verbose_name='Horário de Abertura'),
        ),
        migrations.AddField(
            model_name='unidade',
            name='horarioFechamento',
            field=models.TimeField(null=True, verbose_name='Horário de Fechamento'),
        ),
        migrations.AlterField(
            model_name='unidade',
            name='address',
            field=models.CharField(max_length=200, null=True, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='unidade',
            name='addressNumber',
            field=models.CharField(max_length=10, null=True, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='unidade',
            name='city',
            field=models.CharField(max_length=100, null=True, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='unidade',
            name='cnpj',
            field=models.CharField(max_length=18, null=True, verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='unidade',
            name='codPessEmpresa',
            field=models.CharField(max_length=50, null=True, verbose_name='Código da Empresa'),
        ),
        migrations.AlterField(
            model_name='unidade',
            name='district',
            field=models.CharField(max_length=100, null=True, verbose_name='Bairro'),
        ),
        migrations.AlterField(
            model_name='unidade',
            name='funciona_domingo',
            field=models.BooleanField(default=False, verbose_name='Funciona Domingo'),
        ),
        migrations.AlterField(
            model_name='unidade',
            name='funciona_feriados',
            field=models.BooleanField(default=False, verbose_name='Funciona em Feriados'),
        ),
        migrations.AlterField(
            model_name='unidade',
            name='funciona_quarta',
            field=models.BooleanField(default=False, verbose_name='Funciona Quarta-feira'),
        ),
        migrations.AlterField(
            model_name='unidade',
            name='funciona_quinta',
            field=models.BooleanField(default=False, verbose_name='Funciona Quinta-feira'),
        ),
        migrations.AlterField(
            model_name='unidade',
            name='funciona_sabado',
            field=models.BooleanField(default=False, verbose_name='Funciona Sábado'),
        ),
        migrations.AlterField(
            model_name='unidade',
            name='funciona_segunda',
            field=models.BooleanField(default=False, verbose_name='Funciona Segunda-feira'),
        ),
        migrations.AlterField(
            model_name='unidade',
            name='funciona_sexta',
            field=models.BooleanField(default=False, verbose_name='Funciona Sexta-feira'),
        ),
        migrations.AlterField(
            model_name='unidade',
            name='funciona_terca',
            field=models.BooleanField(default=False, verbose_name='Funciona Terça-feira'),
        ),
        migrations.AlterField(
            model_name='unidade',
            name='horario_domingo_fim',
            field=models.TimeField(blank=True, null=True, verbose_name='Fim Domingo'),
        ),
        migrations.AlterField(
            model_name='unidade',
            name='horario_domingo_inicio',
            field=models.TimeField(blank=True, null=True, verbose_name='Início Domingo'),
        ),
        migrations.AlterField(
            model_name='unidade',
            name='horario_quarta_fim',
            field=models.TimeField(blank=True, null=True, verbose_name='Fim Quarta-feira'),
        ),
        migrations.AlterField(
            model_name='unidade',
            name='horario_quarta_inicio',
            field=models.TimeField(blank=True, null=True, verbose_name='Início Quarta-feira'),
        ),
        migrations.AlterField(
            model_name='unidade',
            name='horario_quinta_fim',
            field=models.TimeField(blank=True, null=True, verbose_name='Fim Quinta-feira'),
        ),
        migrations.AlterField(
            model_name='unidade',
            name='horario_quinta_inicio',
            field=models.TimeField(blank=True, null=True, verbose_name='Início Quinta-feira'),
        ),
        migrations.AlterField(
            model_name='unidade',
            name='horario_sabado_fim',
            field=models.TimeField(blank=True, null=True, verbose_name='Fim Sábado'),
        ),
        migrations.AlterField(
            model_name='unidade',
            name='horario_sabado_inicio',
            field=models.TimeField(blank=True, null=True, verbose_name='Início Sábado'),
        ),
        migrations.AlterField(
            model_name='unidade',
            name='horario_segunda_fim',
            field=models.TimeField(blank=True, null=True, verbose_name='Fim Segunda-feira'),
        ),
        migrations.AlterField(
            model_name='unidade',
            name='horario_segunda_inicio',
            field=models.TimeField(blank=True, null=True, verbose_name='Início Segunda-feira'),
        ),
        migrations.AlterField(
            model_name='unidade',
            name='horario_sexta_fim',
            field=models.TimeField(blank=True, null=True, verbose_name='Fim Sexta-feira'),
        ),
        migrations.AlterField(
            model_name='unidade',
            name='horario_sexta_inicio',
            field=models.TimeField(blank=True, null=True, verbose_name='Início Sexta-feira'),
        ),
        migrations.AlterField(
            model_name='unidade',
            name='horario_terca_fim',
            field=models.TimeField(blank=True, null=True, verbose_name='Fim Terça-feira'),
        ),
        migrations.AlterField(
            model_name='unidade',
            name='horario_terca_inicio',
            field=models.TimeField(blank=True, null=True, verbose_name='Início Terça-feira'),
        ),
        migrations.AlterField(
            model_name='unidade',
            name='nome',
            field=models.CharField(max_length=200, null=True, verbose_name='Nome da Unidade'),
        ),
        migrations.AlterField(
            model_name='unidade',
            name='postalCode',
            field=models.CharField(max_length=9, null=True, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='unidade',
            name='state',
            field=models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2, null=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='unidade',
            name='vagasLivres',
            field=models.PositiveIntegerField(default=0, null=True, verbose_name='Vagas Livres'),
        ),
        migrations.AlterField(
            model_name='unidade',
            name='vagasManobráveis',
            field=models.PositiveIntegerField(default=0, null=True, verbose_name='Vagas Manobráveis'),
        ),
        migrations.AlterField(
            model_name='unidade',
            name='vagasPresas',
            field=models.PositiveIntegerField(default=0, null=True, verbose_name='Vagas Presas'),
        ),
        migrations.CreateModel(
            name='Patio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Pátio')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patios', to='core.unidade', verbose_name='Unidade')),
            ],
            options={
                'verbose_name': 'Pátio',
                'verbose_name_plural': 'Pátios',
            },
        ),
        migrations.CreateModel(
            name='Vaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(verbose_name='Quantidade de Vagas')),
                ('patio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vagas', to='core.patio', verbose_name='Pátio')),
                ('tipo_veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.tipoveiculo', verbose_name='Tipo de Veículo')),
            ],
            options={
                'verbose_name': 'Vaga',
                'verbose_name_plural': 'Vagas',
            },
        ),
    ]
