# Generated by Django 5.2.5 on 2025-10-31 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_unidade_options_remove_unidade_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unidade',
            name='horarioAbertura',
        ),
        migrations.RemoveField(
            model_name='unidade',
            name='horarioFechamento',
        ),
        migrations.RemoveField(
            model_name='unidade',
            name='vagasLivres',
        ),
        migrations.RemoveField(
            model_name='unidade',
            name='vagasManobráveis',
        ),
        migrations.RemoveField(
            model_name='unidade',
            name='vagasPresas',
        ),
    ]
